language: python
python:
- "3.6"
- "2.7"

before_install:
  # Upgrade pip setuptools and wheel
  - pip install -U wheel setuptools coveralls

install:
- pip install -e .[testing,pre-commit]
- reentry scan -r aiida

script:
  - pre-commit install; pre-commit run --all-files || ( git status --short; git diff ; exit 1 );
